apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-ext-deployment
  labels:
    app: service-ext-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-ext-app
      version: v1
  template:
    metadata:
      labels:
        app: service-ext-app
        version: v1
    spec:
      containers:
        - name: service-ext-container
          image: webngt/service-ext:0.0.6
          imagePullPolicy: Always
          command: ["java"]
          args:
            - -Xms32m
            - -Xmx32m
            -  -jar 
            - app.jar
          ports:
            - containerPort: 8082
          securityContext:
            runAsUser: 1000